### ISSUE TITLE
create controller in module to allow it to be added in admin menu

### ISSUE THREAD

**Issue by smarterweb** [thirtybees/productcomments#15]
either change the install function to add this module to the admin menu (maybe under customers) 
or
add the following code to \modules\productcomments\controllers\admin\productcomments.php (create new if not exists)

<?php

class ProductCommentsController extends AdminController {

    public function __construct() {
        $module_name = "productcomments";
        Tools::redirectAdmin('index.php?controller=AdminModules&configure=' . $module_name . '&token=' . Tools::getAdminTokenLite('AdminModules'));
    }

}

**Comment by Dh42** [comment]
I am closing this, not because it is not a good idea, but because we are starting to look at redesigning the back office and we are wanting to integrate most modules this way. So this is something that will come in the future of most all modules, we want to make the module page just for installing modules, not for working with them.
